import { APP_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, USER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const appsNavigationConfig: NavigationTree[] = [
    {
        key: 'apps',
        path: '',
        title: 'APPS',
        translateKey: 'nav.apps',
        icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
            {
                key: 'appsSales.dashboard',
                        path: `${APP_PREFIX_PATH}/sales/dashboard`,
                        title: 'Dashboard',
                        translateKey: 'nav.appsSales.dashboard',
                        icon: 'sales',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
            },
            {
                key: 'apps.project',
                path: '',
                title: 'Saloons',
                translateKey: 'nav.appsProject.project',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    // {
                    //     key: 'appsProject.dashboard',
                    //     path: `${APP_PREFIX_PATH}/project/dashboard`,
                    //     title: 'Dashboard',
                    //     translateKey: 'nav.appsProject.dashboard',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'appsProject.projectList',
                        path: `${APP_PREFIX_PATH}/project/project-list`,
                        title: 'Saloons List',
                        translateKey: 'nav.appsProject.projectList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsProject.categoryList',
                    //     path: `${APP_PREFIX_PATH}/project/category-list`,
                    //     title: 'Categories List',
                    //     translateKey: 'nav.appsProject.categoryList',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsProject.scrumBoard',
                    //     path: `${APP_PREFIX_PATH}/project/scrum-board`,
                    //     title: 'Scrum Board',
                    //     translateKey: 'nav.appsProject.scrumBoard',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsProject.issue',
                    //     path: `${APP_PREFIX_PATH}/project/issue`,
                    //     title: 'Issue',
                    //     translateKey: 'nav.appsProject.issue',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },
            {
                key: 'apps.clinic',
                path: '',
                title: 'Clinics',
                translateKey: 'nav.appsProject.clinics',
                icon: 'clinic',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsProject.clinicsList',
                        path: `${APP_PREFIX_PATH}/project/clinics-list`,
                        title: 'Clinics List',
                        translateKey: 'nav.appsProject.clinicsList',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsBook',
                path: ``,
                title: 'Bookings',
                translateKey: 'nav.appsBook.book',
                icon: 'bookings',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsBook.bookings',
                        path: `${APP_PREFIX_PATH}/bookings`,
                        title: 'Bookings List',
                        translateKey: 'nav.appsBook.bookings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.crm',
                path: '',
                title: 'Users',
                translateKey: 'nav.appsCrm.crm',
                icon: 'crm',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    // {
                    //     key: 'appsCrm.dashboard',
                    //     path: `${APP_PREFIX_PATH}/crm/dashboard`,
                    //     title: 'Dashboard',
                    //     translateKey: 'nav.appsCrm.dashboard',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsCrm.calendar',
                    //     path: `${APP_PREFIX_PATH}/crm/calendar`,
                    //     title: 'Calendar',
                    //     translateKey: 'nav.appsCrm.calendar',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'appsCrm.customers',
                        path: `${APP_PREFIX_PATH}/staff`,
                        title: 'Users List',
                        translateKey: 'nav.appsCrm.customers',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsCrm.customerDetails',
                    //     path: `${APP_PREFIX_PATH}/crm/customer-details?id=8`,
                    //     title: 'User Details',
                    //     translateKey: 'nav.appsCrm.customerDetails',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsCrm.mail',
                    //     path: `${APP_PREFIX_PATH}/crm/mail`,
                    //     title: 'Mail',
                    //     translateKey: 'nav.appsCrm.mail',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },
            // {
            //     key: 'apps.crypto',
            //     path: '',
            //     title: 'Crypto',
            //     translateKey: 'nav.appsCrypto.crypto',
            //     icon: 'crypto',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
            //         {
            //             key: 'appsCrypto.dashboard',
            //             path: `${APP_PREFIX_PATH}/crypto/dashboard`,
            //             title: 'Dashboard',
            //             translateKey: 'nav.appsCrypto.dashboard',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrypto.portfolio',
            //             path: `${APP_PREFIX_PATH}/crypto/portfolio`,
            //             title: 'Portfolio',
            //             translateKey: 'nav.appsCrypto.portfolio',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrypto.market',
            //             path: `${APP_PREFIX_PATH}/crypto/market`,
            //             title: 'Market',
            //             translateKey: 'nav.appsCrypto.market',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //         {
            //             key: 'appsCrypto.wallets',
            //             path: `${APP_PREFIX_PATH}/crypto/wallets`,
            //             title: 'Wallets',
            //             translateKey: 'nav.appsCrypto.wallets',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },
            // {
            //     key: 'apps.knowledgeBase',
            //     path: '',
            //     title: 'FAQs',
            //     translateKey: 'nav.appsknowledgeBase.knowledgeBase',
            //     icon: 'knowledgeBase',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
                    // {
                    //     key: 'appsknowledgeBase.helpCenter',
                    //     path: `${APP_PREFIX_PATH}/knowledge-base/help-center`,
                    //     title: 'Help Center',
                    //     translateKey: 'nav.appsknowledgeBase.helpCenter',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsknowledgeBase.article',
                    //     path: `${APP_PREFIX_PATH}/knowledge-base/article?id=rZjCbSyae5`,
                    //     title: 'Article',
                    //     translateKey: 'nav.appsknowledgeBase.article',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsknowledgeBase.manageArticles',
                    //     path: `${APP_PREFIX_PATH}/knowledge-base/manage-articles`,
                    //     title: 'Manage Articles',
                    //     translateKey: 'nav.appsknowledgeBase.manageArticles',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsknowledgeBase.manageFAQs',
                    //     path: `${APP_PREFIX_PATH}/knowledge-base/manage-faqs`,
                    //     title: 'Manage FAQs',
                    //     translateKey: 'nav.appsknowledgeBase.manageFAQs',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsknowledgeBase.editArticle',
                    //     path: `${APP_PREFIX_PATH}/knowledge-base/edit-article?id=rZjCbSyae5&categoryLabel=Survey&categoryValue=survey`,
                    //     title: 'Edit Article',
                    //     translateKey: 'nav.appsknowledgeBase.editArticle',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                // ],
            // },
            {
                key: 'apps.banners',
                path: '',
                title: 'Banners',
                translateKey: 'nav.banners.banner',
                icon: 'banner',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsBanners.manageBanners',
                        path: `${APP_PREFIX_PATH}/offers/manage-offers`,
                        title: 'Manage Banners',
                        translateKey: 'nav.banners.manageBanners',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'appsPages.pages',
                path: '',
                title: 'Pages',
                translateKey: 'nav.pages.pages',
                icon: 'ppPages',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsPages.managePages',
                        path: `${APP_PREFIX_PATH}/pages/manage-pages`,
                        title: 'Manage Pages',
                        translateKey: 'nav.pages.managePages',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsPages.editPage',
                    //     path: `${APP_PREFIX_PATH}/pages/edit-page?id=rZjCbSyae5`,
                    //     title: 'Edit Page',
                    //     translateKey: 'nav.pages.editPage',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },
            {
                key: 'apps.account',
                path: '',
                title: 'Account',
                translateKey: 'nav.appsAccount.account',
                icon: 'account',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAccount.settings',
                        path: `${APP_PREFIX_PATH}/account/settings/profile`,
                        title: 'Settings',
                        translateKey: 'nav.appsAccount.settings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsAccount.invoice',
                    //     path: `${APP_PREFIX_PATH}/account/invoice/36223`,
                    //     title: 'Invoice',
                    //     translateKey: 'nav.appsAccount.invoice',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    {
                        key: 'appsAccount.activityLog',
                        path: `${APP_PREFIX_PATH}/account/activity-log`,
                        title: 'Activity Log',
                        translateKey: 'nav.appsAccount.activityLog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsAccount.kycForm',
                    //     path: `${APP_PREFIX_PATH}/account/kyc-form`,
                    //     title: 'KYC Form',
                    //     translateKey: 'nav.appsAccount.kycForm',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },
        ],
    },
]

export default appsNavigationConfig
